name: Publish apt-tools-prod to R2
# Trigger on pushes to main/release that modify repo/public/
on:
  push:
    branches:
      - main
      - release
    paths:
      - 'apt-tools-prod/repo/public/**'
      - '.github/workflows/publish-apt.yml'
      - '.github/workflows/r2.yml'

jobs:
  publish-apt:
    uses: ./.github/workflows/r2.yml
    with:
      path: apt-tools-prod/repo/public/
      lfs: true
      target_dir: apt-tools-prod/
    secrets: inherit
