name: Publish yum-tools-prod to R2
# Trigger on pushes to main/release that modify public/
on:
  push:
    branches:
      - main
      - release
    paths:
      - 'yum-tools-prod/public/**'
      - '.github/workflows/publish-yum.yml'
      - '.github/workflows/r2.yml'

jobs:
  publish-yum:
    uses: ./.github/workflows/r2.yml
    with:
      path: yum-tools-prod/public/
      lfs: true
      target_dir: yum-tools-prod/
    secrets: inherit
