name: Publish landing page to R2
# Trigger on pushes to main/release that modify public/
on:
  push:
    branches:
      - main
      - release
    paths:
      - 'templates/landing/**'

jobs:
  publish-yum:
    uses: ./.github/workflows/r2.yml
    with:
      path: landing/
    secrets: inherit
